### ISSUE TITLE
m1pro sonoma打开后无效

### ISSUE THREAD

**Issue by captainnx** [alaneuler/batteryKid#1]

**Comment by alaneuler** [comment]
/tmp 目录下有 batteryKidPrivilegeHelper 开头的文件吗？有的话内容发一下～

如果没有的话，得用 Console 看下日志了（看看有没有相关报错），过滤条件为 Process：batteryKid，
如下：
<img width="1122" alt="image" src="https://github.com/alaneuler/batteryKid/assets/8054939/61e124d5-5201-4ecc-a60b-260bdf290139">

**Comment by alaneuler** [comment]
Fixed in v1.1.1
