### ISSUE TITLE
Brew Package Manager

### ISSUE THREAD

**Issue by is-ege** [alaneuler/batteryKid#18]
Hello, thanks for the great project.
I was wondering is it possible to add it to brew so that updating and managing the program is easier?

**Comment by alaneuler** [comment]
> Hello, thanks for the great project.
> 
> I was wondering is it possible to add it to brew so that updating and managing the program is easier?

hi @realdep I am not familiar with homebrew packaging and distribution. Also, batteryKid comes with built-in update capabilities, so Maybe I'll consider in the future.
