### ISSUE TITLE
The icon disappears from the menu bar in inactive spaces

### ISSUE THREAD

**Issue by rimas-kudelis** [alaneuler/batteryKid#21]
I have multiple screens, and I noticed that the battery icon disappears from the menu bar in my main screen when I switch to a window in a different screen.

No other menu bar icons behave like this.

**Comment by alaneuler** [comment]
I don't use multiple screens, maybe I need some time to reproduce this problem.

**Comment by rimas-kudelis** [comment]
Somehow it isn't disappearing to me either, at least right now. But I'll check later with two external displays again.

**Comment by alaneuler** [comment]
Do you use bartender or similar app?

**Comment by rimas-kudelis** [comment]
Hm, okay, I think I can't reproduce this anymore. The widget is heavily greyed out on inactive screens, but it's still there in place.
